version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    env_file: 
      - ./.env
  # rest-app:
  #   restart: always
  #   build: .
  #   image: swift-dynamic-test
  #   ports:
  #     - 8081:8081
  #   links:
  #     - mongo
  #   env_file: 
  #     - ./.env
