version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    env_file: 
      - ./.env
  rest-app:
    restart: always
    build: .
    image: swift-dynamic-test
    ports:
      - ${EXPORE_PORT}:${PORT}
    env_file: 
      - ./.env
    links:
      - mongo
